name: Build and Push Airflow

on:
  push:
    paths:
      - 'docker/airflow/**'
      - 'dags/**'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Airflow image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/airflow-custom:latest docker/airflow
          docker push ${{ secrets.DOCKER_USERNAME }}/airflow-custom:latest
